### ISSUE TITLE
Correct User object creation

### ISSUE THREAD

**Issue by allejo** [allejo/BZBBAuthenticationBundle#1]
When a new BZFlag user logs into the website and doesn't have an account, the Authenticator will create an account for them along with an object to pass on to the Symfony app. This bundle has a [base User entity](https://github.com/allejo/BZBBAuthenticationBundle/blob/master/Entity/User.php) for Symfony apps to extend. However, if the authenticator creates one of these objects, the Symfony app won't be able to work with `AppBundle:User` if it exists.

This bundle dispatches events so the Symfony app can listen and set any custom fields necessary that are required, so we shouldn't be worried about not supporting `AppBundle:User` entities. i.e. Create an event listener in your Symfony app that'll call the setters for non-nullable properties.

That brings us to this wonderfully nasty hack. I added this hack just to get things working for now, but I'm sure there must be a correct way of doing this. Thoughts?

https://github.com/allejo/BZBBAuthenticationBundle/blob/2bf9dba5251225ba663ef0603daacf427983fd9a/Security/BZBBAuthenticator.php#L139-L150

/cc @kongr45gpen

**Comment by kongr45gpen** [comment]
The following method seems to be returning the currently active User class:
```php
$this->entityManager->getRepository('AppBundle:User')->getClassName()
```

However, since Doctrine fiddles with entity classes by creating subclasses so that some techniques for lazy loading can be applied, the result of this method might differ from the result of the 7-line hack.

**Comment by allejo** [comment]
Would that function return the bundle's User class if the given Symfony app doesn't implement their own `AppBundle:User` or should it be a requirement to implement an `AppBundle:User`?

**Comment by allejo** [comment]
Or can there be a check to see if `AppBundle:User` exists and if not, all back to the bundle entity? Or what if it's not called `AppBundle:User`?

**Comment by kongr45gpen** [comment]
Ah, you're right — apparently, the user class is set up in the configuration of the Security bundle, and is only passed internally - so there's probably no way of finding out the user class other than the one you showed above.

![image](https://user-images.githubusercontent.com/720678/33235698-a4ca96ca-d246-11e7-8208-3b83397220c7.png)

Would PHP's `get_class()` function be able to do the trick?

**Comment by allejo** [comment]
Hmm `get_class()` would only get us the class for an object that's already been created, not one that we need to create for a new registration. I'll explore what other bundles do to see how they achieve something like this, if not the creation of an `AppBundle:User` could be required for using this bundle?

**Comment by allejo** [comment]
Ah hah! So it seems like a requirement of FOSUserBundle is that you [create your own User entity when you set up the bundle](https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-3-create-your-user-class), so we can just follow that example and require devs to create a User entity instead of the ugly hack currently in place.

Edit: It also requires you to specify the [entity in the bundle configuration](https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle), so I think it's sane to follow this practice

**Comment by allejo** [comment]
Thanks for the help, @kongr45gpen I think this should work in a more sane manner now 👍
